trained_vqvae_model_path: saved_models/model_down_infonce_noise_12_18/checkpoints/final_model.pth
base_path: IQ_normalized_data/June_downsampling/
mask_ratio: 0.0
compression_factor: 4
use_gpu: true
gpu: 0
use_multi_gpu: false
data_channels: 2
# acc_threshold: 0.3
revin: true
noise_level: 0.1
general_seed: 51



